# Generated by Django 5.0.4 on 2024-05-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_legal_proceedings_decision_document_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=255, null=True)),
                ("position", models.CharField(max_length=255, null=True)),
                ("education_institution", models.CharField(max_length=255, null=True)),
                ("education_specialty", models.CharField(max_length=255, null=True)),
                (
                    "education_diploma_details",
                    models.CharField(max_length=255, null=True),
                ),
                ("spouse_name", models.CharField(max_length=255, null=True)),
                ("spouse_birth_year", models.IntegerField(null=True)),
                ("spouse_occupation", models.CharField(max_length=255, null=True)),
                ("legal_entity_name", models.CharField(max_length=255, null=True)),
                ("legal_entity_activity", models.CharField(max_length=255, null=True)),
                ("legal_entity_share_percentage", models.FloatField(null=True)),
                ("employment_period", models.CharField(max_length=255, null=True)),
                (
                    "employment_organization",
                    models.CharField(max_length=255, null=True),
                ),
                ("employment_position", models.CharField(max_length=255, null=True)),
                ("employment_disciplinary_actions", models.BooleanField(default=False)),
                (
                    "employment_termination_reason",
                    models.CharField(max_length=255, null=True),
                ),
                ("audit_organization", models.CharField(max_length=255, null=True)),
                ("audit_year", models.IntegerField(null=True)),
                ("audit_financial_report", models.CharField(max_length=255, null=True)),
                (
                    "investment_committee_period",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "investment_committee_organization",
                    models.CharField(max_length=255, null=True),
                ),
                ("legal_proceedings_involved", models.BooleanField(default=False)),
                ("legal_proceedings_date", models.DateField(blank=True, null=True)),
                (
                    "legal_proceedings_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("legal_proceedings_issue", models.TextField(blank=True, null=True)),
                ("legal_proceedings_decision", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_data",
                        to="api.document",
                    ),
                ),
            ],
        ),
    ]
