# Generated by Django 5.0.4 on 2024-05-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_documentdata_options_documentdata_citizenship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="education_period",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
